### ISSUE TITLE
add health check for application certificates

### ISSUE THREAD

**Issue by pdpinch** [mitodl/django-server-status#33]
would be useful for OVS 

was not useful for lmod_proxy because it's not django.

**Comment by pdpinch** [comment]
@mitodl/devops what should this return? The cert's expiration date?

**Comment by pdpinch** [comment]
@mitodl/devops I might assign this to Amir next sprint. What should the API return? What does it return for lmod_proxy?

**Comment by blarghmatey** [comment]
It currently returns the expiration timestamp for the certificate, and if it's < N days until expiration the `status` key in the returned JSON is set to `warn`

https://github.com/mitodl/lmod_proxy/blob/master/lmod_proxy/web.py#L74-L77
