### ISSUE TITLE
Unable to install using pip

### ISSUE THREAD

**Issue by noisecapella** [mitodl/django-server-status#6]
I get this message when running `pip install django-server-status`:

    You are using pip version 7.0.1, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting django-server-status
      Could not find a version that satisfies the requirement django-server-status (from versions: )
    No matching distribution found for django-server-status

Is there more work that needs to be done to allow for this?

**Comment by pdpinch** [comment]
Looks like we didn't upload the package?

```
python setup.py sdist upload
```

maybe?

**Comment by noisecapella** [comment]
It looks like this is fixed now, CCXCon can use it successfully from pip: https://github.com/mitodl/teachersportal/pull/336
